# Site settings
title: Small World Stories 
email: sjr1991@gmail.com
description: Small World Stories - a sharing blog (coming soon)
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://smallworldstories.today" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/Jaff/stories
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/warnfrcopyeditr

# Build settings
markdown: kramdown
